plugins {
    id 'java-library'
}

group = 'com.dropbox.conductor'
version = '0.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'com.dropbox.core:dropbox-core-sdk:8.0.2'

    implementation 'org.conductoross:conductor-client:VERSION'

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
